!wireinject
// +build !wireinject

package p // Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

// Injectors from wire.go:

import (
	"github.com/google/wire"
)

func injector1() {

}
