// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package interfaces

// Injectors from wire.go:

func InjectStringAppendingFile(id FileID, name FileName, path FilePath, content FileContent) StringAppendingFile {
	stringAppendingFile := NewStringAppendingFile(id, name, path, content)
	return stringAppendingFile
}

func InjectStringRepalceFile(id FileID, name FileName, path FilePath, content FileContent) StringReplaceFile {
	stringReplaceFile := NewStringReplaceFile(id, name, path, content)
	return stringReplaceFile
}
